### ISSUE TITLE
Rewirte in python for 3B

### ISSUE THREAD

**Issue by WeisongZhao** [edrosten/threeB#2]
Hi, I am trying to rewirite the 3B into python, and the best way is to read your code deeply. Could you help me to find the core of code? BTW, how did you relate the fluorophore positions to the real data (image sequence), did you convolute the PSF to the flurophore, I'm a little confused.
Thank you!

**Comment by edrosten** [comment]
Hi,

What precisely are you trying to achieve here? 3B is a very heavyweight piece of computation code. The big video at the end of [this](http://www.coxphysics.com/3b/paper.html) page took many hours on a cluster of hundreds of machines. A typical small chunk giving a single image result (i.e. not a video) takes somewhere in the region of 4-6 hours. The resulting code in python is likely to be too slow to be practical.

If you want to dig into the code, it's pretty well documented with Doxygen so a good starting point is to run that so you get a cross reference then follow the code through from multispot5_headless.cc

If you're interested in actually analyzing images, then I'd also recommend (Marsh et.al's HAWK algorithm)[https://experiments.springernature.com/articles/10.1038/s41592-018-0072-5], (code here)[https://coxphysics.com]. It's much easier to use because you don't run the risk of getting artefacts and it's vastly faster than 3B (using HAWK+thunderstorm, you can process in minutes what would take hours on a good sized cluster with 3B).

**Comment by WeisongZhao** [comment]
Many thanks for your reply! 
I just want to look inside the Bayesian model of 3B, and the best way I thought, is to write the solution by myself. The heavyweight piece of computation will not be in my consideration (small simulation data, GPU accelaration, and the idle computers). 
Best,
